from setuptools import setup, find_packages

setup(
    name="ShareWave",
    version="0.1",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        'atomicwrites==1.4.1',
        'attrs==24.2.0',
        'certifi==2024.7.4',
        'chardet==4.0.0',
        'colorama==0.4.6',
        'docopt==0.6.2',
        'idna==2.10',
        'iniconfig==2.0.0',
        'packaging==24.1',
        'pluggy==0.13.1',
        'py==1.11.0',
        'pure-eval==0.2.3',
        'pywin32==306',
        'pyzmq==26.1.1',
        'requests==2.25.1',
        'six==1.16.0',
        'stack-data==0.6.3',
        'toml==0.10.2',
        'tornado==6.4.1',
        'traitlets==5.14.3',
        'urllib3==1.26.19',
        'webencodings==0.5.1',
        'yarg==0.1.9',
    ],
    entry_points={
        "console_scripts": [
            "sharewave-tracker=tracker:main",
            "sharewave-client=client_handler:main",
        ],
    },
    python_requires='>=3.6',
)
